version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_LOG_CONSOLE: "true"  
      MYSQL_GENERAL_LOG: "1"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/database/MySQL/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql-data: